/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/planet.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[46.24, 58.93, 0]} rotation={[0.62, -0.08, -0.23]}>
        <directionalLight intensity={6.64} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-1.29, 47.34, 56.24]} rotation={[0.8, 0, 0]} scale={[26.35, 26.35, 26.35]}>
        <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={35.9} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-3.87, 13.34, -21.86]} rotation={[-1.04, -0.06, 0.07]}>
        <directionalLight intensity={4.6} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-24.22, 5.46, -27.59]} rotation={[1.68, -0.09, 2.45]}>
        <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={35.9} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh geometry={nodes.Sphere001.geometry} material={materials['DesertPlanet.001']} scale={371.81} />
      <group position={[0.09, 0.03, 0.61]} rotation={[-1.57, 0.87, 0]} scale={[0.54, 1.26, 0.54]}>
        <mesh geometry={nodes.Cylinder088.geometry} material={materials['Material.074']} />
        <mesh geometry={nodes.Cylinder088_1.geometry} material={nodes.Cylinder088_1.material} />
        <group position={[-15.44, -0.67, -9.17]} rotation={[Math.PI, -1.04, Math.PI]} scale={[2.01, 1.31, 2.24]}>
          <mesh geometry={nodes.Cube036.geometry} material={materials['Material.075']} />
          <mesh geometry={nodes.Cube036_1.geometry} material={materials['Material.076']} />
          <mesh geometry={nodes.Cube036_2.geometry} material={nodes.Cube036_2.material} />
          <mesh geometry={nodes.Cube036_3.geometry} material={materials['Material.077']} />
          <mesh geometry={nodes.Cube036_4.geometry} material={nodes.Cube036_4.material} />
          <mesh geometry={nodes.Cube036_5.geometry} material={materials['Material.078']} />
          <mesh geometry={nodes.Cube036_6.geometry} material={nodes.Cube036_6.material} />
        </group>
        <group position={[-9.08, -0.67, -15.5]} rotation={[0, 0.54, 0]} scale={[2.01, 1.31, 2.24]}>
          <mesh geometry={nodes.Cube037.geometry} material={materials['Material.079']} />
          <mesh geometry={nodes.Cube037_1.geometry} material={materials['Material.080']} />
          <mesh geometry={nodes.Cube037_2.geometry} material={materials['Material.081']} />
          <mesh geometry={nodes.Cube037_3.geometry} material={materials['Material.082']} />
          <mesh geometry={nodes.Cube037_4.geometry} material={materials['Material.083']} />
          <mesh geometry={nodes.Cube037_5.geometry} material={materials['Circulito.003']} />
          <mesh geometry={nodes.Cube037_6.geometry} material={materials['Material.084']} />
          <mesh geometry={nodes.Cube037_7.geometry} material={materials['Material.085']} />
          <mesh geometry={nodes.Cube037_8.geometry} material={nodes.Cube037_8.material} />
          <mesh geometry={nodes.Cube037_9.geometry} material={materials['Material.086']} />
          <mesh geometry={nodes.Cube037_10.geometry} material={materials['Material.087']} />
        </group>
        <group position={[-0.05, -0.67, -17.85]} scale={[2.01, 1.31, 2.24]}>
          <mesh geometry={nodes.Cube038.geometry} material={nodes.Cube038.material} />
          <mesh geometry={nodes.Cube038_1.geometry} material={nodes.Cube038_1.material} />
          <mesh geometry={nodes.Cube038_2.geometry} material={nodes.Cube038_2.material} />
          <mesh geometry={nodes.Cube038_3.geometry} material={nodes.Cube038_3.material} />
        </group>
        <group position={[17.92, -0.67, 0.03]} rotation={[0, -0.01, 0]} scale={[2.24, 1.31, 2.01]}>
          <mesh geometry={nodes.Cube039.geometry} material={nodes.Cube039.material} />
          <mesh geometry={nodes.Cube039_1.geometry} material={nodes.Cube039_1.material} />
          <mesh geometry={nodes.Cube039_2.geometry} material={nodes.Cube039_2.material} />
          <mesh geometry={nodes.Cube039_3.geometry} material={nodes.Cube039_3.material} />
        </group>
        <mesh
          geometry={nodes.Cube004.geometry}
          material={nodes.Cube004.material}
          position={[-14.34, -0.16, 3.93]}
          rotation={[0, 0.27, 0]}
          scale={[0.49, 0.49, 0.27]}
        />
        <mesh
          geometry={nodes.Cube005.geometry}
          material={nodes.Cube005.material}
          position={[-14.35, -0.16, -3.92]}
          rotation={[0, -0.25, 0]}
          scale={[0.49, 0.49, 0.27]}
        />
        <mesh
          geometry={nodes.Cube006.geometry}
          material={nodes.Cube006.material}
          position={[-10.57, -0.16, -10.45]}
          rotation={[0, -0.74, 0]}
          scale={[0.49, 0.49, 0.27]}
        />
        <mesh
          geometry={nodes.Cube007.geometry}
          material={nodes.Cube007.material}
          position={[-3.9, -0.16, -14.35]}
          rotation={[0, -1.27, 0]}
          scale={[0.49, 0.49, 0.27]}
        />
        <mesh
          geometry={nodes.Cube008.geometry}
          material={nodes.Cube008.material}
          position={[4.03, -0.16, -14.31]}
          rotation={[Math.PI, -1.3, Math.PI]}
          scale={[0.49, 0.49, 0.27]}
        />
        <mesh
          geometry={nodes.Cube009.geometry}
          material={nodes.Cube009.material}
          position={[10.53, -0.16, -10.5]}
          rotation={[Math.PI, -0.79, Math.PI]}
          scale={[0.49, 0.49, 0.27]}
        />
        <mesh
          geometry={nodes.Cube010.geometry}
          material={nodes.Cube010.material}
          position={[14.35, -0.16, -3.91]}
          rotation={[Math.PI, -0.27, Math.PI]}
          scale={[0.49, 0.49, 0.27]}
        />
        <mesh
          geometry={nodes.Cube012.geometry}
          material={nodes.Cube012.material}
          position={[10.51, -0.16, 10.52]}
          rotation={[-Math.PI, 0.78, -Math.PI]}
          scale={[0.49, 0.49, 0.27]}
        />
        <mesh
          geometry={nodes.Cube013.geometry}
          material={nodes.Cube013.material}
          position={[3.99, -0.16, 14.33]}
          rotation={[-Math.PI, 1.28, -Math.PI]}
          scale={[0.49, 0.49, 0.27]}
        />
        <mesh
          geometry={nodes.Cube014.geometry}
          material={nodes.Cube014.material}
          position={[-3.94, -0.16, 14.34]}
          rotation={[0, 1.3, 0]}
          scale={[0.49, 0.49, 0.27]}
        />
        <mesh
          geometry={nodes.Cube015.geometry}
          material={nodes.Cube015.material}
          position={[-10.48, -0.16, 10.55]}
          rotation={[0, 0.79, 0]}
          scale={[0.49, 0.49, 0.27]}
        />
        <group position={[-13.82, -0.16, 3.58]} rotation={[Math.PI / 2, 0, -0.25]} scale={[0.86, 2.03, 0.42]}>
          <mesh geometry={nodes.Cylinder089.geometry} material={nodes.Cylinder089.material} />
          <mesh geometry={nodes.Cylinder089_1.geometry} material={nodes.Cylinder089_1.material} />
        </group>
        <mesh
          geometry={nodes.Cylinder002.geometry}
          material={nodes.Cylinder002.material}
          position={[-14.34, -0.16, 3.93]}
          scale={[0.84, 0.45, 0.84]}
        />
        <group position={[-14.34, -0.16, 3.93]} rotation={[0, 0.27, -Math.PI / 2]} scale={[0.36, 0.99, 0.84]}>
          <mesh geometry={nodes.Cylinder091.geometry} material={nodes.Cylinder091.material} />
          <mesh geometry={nodes.Cylinder091_1.geometry} material={nodes.Cylinder091_1.material} />
        </group>
        <group position={[0, -0.15, -11.14]} rotation={[Math.PI / 2, 0, 0]} scale={[1.07, 1.43, 0.46]}>
          <mesh geometry={nodes.Cylinder092.geometry} material={materials['Material.090']} />
          <mesh geometry={nodes.Cylinder092_1.geometry} material={nodes.Cylinder092_1.material} />
        </group>
        <mesh
          geometry={nodes.Cylinder007.geometry}
          material={nodes.Cylinder007.material}
          position={[0, -0.15, -5.2]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.67, 5.12, 0.29]}
        />
        <mesh
          geometry={nodes.Cylinder008.geometry}
          material={nodes.Cylinder008.material}
          position={[0, -0.15, 2.72]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1.07, 1.06, 0.46]}
        />
        <mesh
          geometry={nodes.Cylinder009.geometry}
          material={nodes.Cylinder009.material}
          position={[1.6, -0.15, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.77, 0.36, 0.33]}
        />
        <mesh
          geometry={nodes.Cylinder010.geometry}
          material={nodes.Cylinder010.material}
          position={[-1.6, -0.15, 0]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.77, 0.36, 0.33]}
        />
        <group position={[-13.72, -0.16, -3.96]} rotation={[Math.PI / 2, 0, 0.26]} scale={[0.86, 2.03, 0.42]}>
          <mesh geometry={nodes.Cylinder099.geometry} material={nodes.Cylinder099.material} />
          <mesh geometry={nodes.Cylinder099_1.geometry} material={nodes.Cylinder099_1.material} />
        </group>
        <mesh
          geometry={nodes.Cylinder012.geometry}
          material={nodes.Cylinder012.material}
          position={[-14.35, -0.16, -3.92]}
          rotation={[0, -0.52, 0]}
          scale={[0.84, 0.45, 0.84]}
        />
        <group position={[-14.35, -0.16, -3.92]} rotation={[0, -0.25, -Math.PI / 2]} scale={[0.36, 0.99, 0.84]}>
          <mesh geometry={nodes.Cylinder101.geometry} material={nodes.Cylinder101.material} />
          <mesh geometry={nodes.Cylinder101_1.geometry} material={nodes.Cylinder101_1.material} />
        </group>
        <group position={[-10, -0.16, -10.2]} rotation={[Math.PI / 2, 0, 0.75]} scale={[0.86, 2.03, 0.42]}>
          <mesh geometry={nodes.Cylinder102.geometry} material={nodes.Cylinder102.material} />
          <mesh geometry={nodes.Cylinder102_1.geometry} material={nodes.Cylinder102_1.material} />
        </group>
        <mesh
          geometry={nodes.Cylinder015.geometry}
          material={nodes.Cylinder015.material}
          position={[-10.57, -0.16, -10.45]}
          rotation={[0, -1.01, 0]}
          scale={[0.84, 0.45, 0.84]}
        />
        <group position={[-10.57, -0.16, -10.45]} rotation={[0, -0.74, -Math.PI / 2]} scale={[0.36, 0.99, 0.84]}>
          <mesh geometry={nodes.Cylinder104.geometry} material={nodes.Cylinder104.material} />
          <mesh geometry={nodes.Cylinder104_1.geometry} material={nodes.Cylinder104_1.material} />
        </group>
        <group position={[-3.53, -0.16, -13.84]} rotation={[Math.PI / 2, 0, 1.28]} scale={[0.86, 2.03, 0.42]}>
          <mesh geometry={nodes.Cylinder105.geometry} material={nodes.Cylinder105.material} />
          <mesh geometry={nodes.Cylinder105_1.geometry} material={nodes.Cylinder105_1.material} />
        </group>
        <mesh
          geometry={nodes.Cylinder018.geometry}
          material={nodes.Cylinder018.material}
          position={[-3.9, -0.16, -14.35]}
          rotation={[0, -1.54, 0]}
          scale={[0.84, 0.45, 0.84]}
        />
        <group position={[-3.9, -0.16, -14.35]} rotation={[0, -1.27, -Math.PI / 2]} scale={[0.36, 0.99, 0.84]}>
          <mesh geometry={nodes.Cylinder107.geometry} material={nodes.Cylinder107.material} />
          <mesh geometry={nodes.Cylinder107_1.geometry} material={nodes.Cylinder107_1.material} />
        </group>
        <group position={[4.06, -0.16, -13.69]} rotation={[Math.PI / 2, 0, 1.86]} scale={[0.86, 2.03, 0.42]}>
          <mesh geometry={nodes.Cylinder108.geometry} material={nodes.Cylinder108.material} />
          <mesh geometry={nodes.Cylinder108_1.geometry} material={nodes.Cylinder108_1.material} />
        </group>
        <mesh
          geometry={nodes.Cylinder021.geometry}
          material={nodes.Cylinder021.material}
          position={[4.03, -0.16, -14.31]}
          rotation={[Math.PI, -1.03, Math.PI]}
          scale={[0.84, 0.45, 0.84]}
        />
        <group position={[4.03, -0.16, -14.31]} rotation={[-Math.PI, -1.3, Math.PI / 2]} scale={[0.36, 0.99, 0.84]}>
          <mesh geometry={nodes.Cylinder110.geometry} material={nodes.Cylinder110.material} />
          <mesh geometry={nodes.Cylinder110_1.geometry} material={nodes.Cylinder110_1.material} />
        </group>
        <group position={[10.25, -0.16, -9.95]} rotation={[Math.PI / 2, 0, 2.37]} scale={[0.86, 2.03, 0.42]}>
          <mesh geometry={nodes.Cylinder111.geometry} material={nodes.Cylinder111.material} />
          <mesh geometry={nodes.Cylinder111_1.geometry} material={nodes.Cylinder111_1.material} />
        </group>
        <mesh
          geometry={nodes.Cylinder024.geometry}
          material={nodes.Cylinder024.material}
          position={[10.53, -0.16, -10.5]}
          rotation={[Math.PI, -0.52, Math.PI]}
          scale={[0.84, 0.45, 0.84]}
        />
        <group position={[10.53, -0.16, -10.5]} rotation={[Math.PI, -0.78, Math.PI / 2]} scale={[0.36, 0.99, 0.84]}>
          <mesh geometry={nodes.Cylinder113.geometry} material={nodes.Cylinder113.material} />
          <mesh geometry={nodes.Cylinder113_1.geometry} material={nodes.Cylinder113_1.material} />
        </group>
        <group position={[13.83, -0.16, -3.57]} rotation={[Math.PI / 2, 0, 2.89]} scale={[0.86, 2.03, 0.42]}>
          <mesh geometry={nodes.Cylinder114.geometry} material={nodes.Cylinder114.material} />
          <mesh geometry={nodes.Cylinder114_1.geometry} material={nodes.Cylinder114_1.material} />
        </group>
        <mesh
          geometry={nodes.Cylinder027.geometry}
          material={nodes.Cylinder027.material}
          position={[14.35, -0.16, -3.91]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.84, 0.45, 0.84]}
        />
        <group position={[14.35, -0.16, -3.91]} rotation={[Math.PI, -0.27, Math.PI / 2]} scale={[0.36, 0.99, 0.84]}>
          <mesh geometry={nodes.Cylinder116.geometry} material={nodes.Cylinder116.material} />
          <mesh geometry={nodes.Cylinder116_1.geometry} material={nodes.Cylinder116_1.material} />
        </group>
        <group position={[9.96, -0.16, 10.24]} rotation={[Math.PI / 2, 0, -2.34]} scale={[0.86, 2.03, 0.42]}>
          <mesh geometry={nodes.Cylinder120.geometry} material={nodes.Cylinder120.material} />
          <mesh geometry={nodes.Cylinder120_1.geometry} material={nodes.Cylinder120_1.material} />
        </group>
        <mesh
          geometry={nodes.Cylinder033.geometry}
          material={nodes.Cylinder033.material}
          position={[10.51, -0.16, 10.52]}
          rotation={[-Math.PI, 1.05, -Math.PI]}
          scale={[0.84, 0.45, 0.84]}
        />
        <group position={[10.51, -0.16, 10.52]} rotation={[Math.PI, 0.79, Math.PI / 2]} scale={[0.36, 0.99, 0.84]}>
          <mesh geometry={nodes.Cylinder122.geometry} material={nodes.Cylinder122.material} />
          <mesh geometry={nodes.Cylinder122_1.geometry} material={nodes.Cylinder122_1.material} />
        </group>
        <group position={[3.63, -0.16, 13.81]} rotation={[Math.PI / 2, 0, -1.85]} scale={[0.86, 2.03, 0.42]}>
          <mesh geometry={nodes.Cylinder123.geometry} material={nodes.Cylinder123.material} />
          <mesh geometry={nodes.Cylinder123_1.geometry} material={nodes.Cylinder123_1.material} />
        </group>
        <mesh
          geometry={nodes.Cylinder036.geometry}
          material={nodes.Cylinder036.material}
          position={[3.99, -0.16, 14.33]}
          rotation={[-Math.PI, 1.55, -Math.PI]}
          scale={[0.84, 0.45, 0.84]}
        />
        <group position={[3.99, -0.16, 14.33]} rotation={[-Math.PI, 1.28, Math.PI / 2]} scale={[0.36, 0.99, 0.84]}>
          <mesh geometry={nodes.Cylinder125.geometry} material={nodes.Cylinder125.material} />
          <mesh geometry={nodes.Cylinder125_1.geometry} material={nodes.Cylinder125_1.material} />
        </group>
        <group position={[-3.97, -0.16, 13.72]} rotation={[Math.PI / 2, 0, -1.29]} scale={[0.86, 2.03, 0.42]}>
          <mesh geometry={nodes.Cylinder126.geometry} material={nodes.Cylinder126.material} />
          <mesh geometry={nodes.Cylinder126_1.geometry} material={nodes.Cylinder126_1.material} />
        </group>
        <mesh
          geometry={nodes.Cylinder039.geometry}
          material={nodes.Cylinder039.material}
          position={[-3.94, -0.16, 14.34]}
          rotation={[0, 1.04, 0]}
          scale={[0.84, 0.45, 0.84]}
        />
        <group position={[-3.94, -0.16, 14.34]} rotation={[0, 1.3, -Math.PI / 2]} scale={[0.36, 0.99, 0.84]}>
          <mesh geometry={nodes.Cylinder128.geometry} material={nodes.Cylinder128.material} />
          <mesh geometry={nodes.Cylinder128_1.geometry} material={nodes.Cylinder128_1.material} />
        </group>
        <group position={[-10.2, -0.16, 9.99]} rotation={[Math.PI / 2, 0, -0.77]} scale={[0.86, 2.03, 0.42]}>
          <mesh geometry={nodes.Cylinder129.geometry} material={nodes.Cylinder129.material} />
          <mesh geometry={nodes.Cylinder129_1.geometry} material={nodes.Cylinder129_1.material} />
        </group>
        <mesh
          geometry={nodes.Cylinder042.geometry}
          material={nodes.Cylinder042.material}
          position={[-10.48, -0.16, 10.55]}
          rotation={[0, 0.52, 0]}
          scale={[0.84, 0.45, 0.84]}
        />
        <group position={[-10.48, -0.16, 10.55]} rotation={[0, 0.79, -Math.PI / 2]} scale={[0.36, 0.99, 0.84]}>
          <mesh geometry={nodes.Cylinder131.geometry} material={nodes.Cylinder131.material} />
          <mesh geometry={nodes.Cylinder131_1.geometry} material={nodes.Cylinder131_1.material} />
        </group>
        <group position={[2.85, 1.33, -0.01]} rotation={[3.14, 0, -1.54]} scale={[2.46, 0.74, 2.52]}>
          <mesh geometry={nodes.Cube053.geometry} material={materials['Material.093']} />
          <mesh geometry={nodes.Cube053_1.geometry} material={materials['Gris ventilaciòn.003']} />
          <mesh geometry={nodes.Cube053_2.geometry} material={materials['negro ventilaciòn.006']} />
          <mesh geometry={nodes.Cube053_3.geometry} material={materials['Negro alas y base.003']} />
          <mesh geometry={nodes.Cube053_4.geometry} material={materials['Blanco arriva.003']} />
          <mesh geometry={nodes.Cube053_5.geometry} material={materials['Metal Back.006']} />
          <mesh geometry={nodes.Cube053_6.geometry} material={materials['Material.094']} />
          <mesh geometry={nodes.Cube053_7.geometry} material={materials['Glass.003']} />
          <mesh geometry={nodes.Cube053_8.geometry} material={materials['Material.095']} />
          <mesh geometry={nodes.Cube053_9.geometry} material={materials['Material.096']} />
          <mesh geometry={nodes.Cube053_10.geometry} material={materials['Material.097']} />
          <mesh geometry={nodes.Cube053_11.geometry} material={materials['Material.098']} />
          <mesh geometry={nodes.Cube053_12.geometry} material={materials['Metal Back.007']} />
          <mesh geometry={nodes.Cube053_13.geometry} material={materials['negro ventilaciòn.007']} />
        </group>
      </group>
      <group position={[25.89, 1.33, -0.95]} rotation={[3.05, 0, -3.11]} scale={[3.33, 0.35, 1.4]}>
        <mesh geometry={nodes.Cube054.geometry} material={materials['Material.104']} />
        <mesh geometry={nodes.Cube054_1.geometry} material={materials['Gris ventilaciòn.004']} />
        <mesh geometry={nodes.Cube054_2.geometry} material={materials['negro ventilaciòn.009']} />
        <mesh geometry={nodes.Cube054_3.geometry} material={materials['Negro alas y base.004']} />
        <mesh geometry={nodes.Cube054_4.geometry} material={materials['Blanco arriva.004']} />
        <mesh geometry={nodes.Cube054_5.geometry} material={materials['Metal Back.009']} />
        <mesh geometry={nodes.Cube054_6.geometry} material={materials['Material.103']} />
        <mesh geometry={nodes.Cube054_7.geometry} material={materials['Glass.004']} />
        <mesh geometry={nodes.Cube054_8.geometry} material={materials['Material.102']} />
        <mesh geometry={nodes.Cube054_9.geometry} material={materials['Material.101']} />
        <mesh geometry={nodes.Cube054_10.geometry} material={materials['Material.100']} />
        <mesh geometry={nodes.Cube054_11.geometry} material={materials['Material.099']} />
        <mesh geometry={nodes.Cube054_12.geometry} material={materials['Metal Back.008']} />
        <mesh geometry={nodes.Cube054_13.geometry} material={materials['negro ventilaciòn.008']} />
      </group>
    </group>
  )
}

useGLTF.preload('/planet.glb')
